- frontend/.gitignore
- frontend/src/app/admin/dashboard/_components/adminProfile.tsx
- frontend/src/app/admin/dashboard/_components/sidebar/consts.ts
- frontend/src/app/admin/dashboard/_components/sidebar/sideBar.tsx
- frontend/src/app/admin/dashboard/_components/sidebar/sideBarMenuItem.tsx
- frontend/src/app/admin/dashboard/_types/adminInfo.ts
- frontend/src/app/admin/dashboard/_types/menuItem.ts
- frontend/src/app/admin/dashboard/page.tsx
관리자 페이지 사이드바 UI 제작 완료
---
- 제대로 동작하지 않을 수 있습니다.
---
closed #16
> Feat/16: 어드민 대시보드 페이지 사이드바 UI 추가

- frontend/src/app/components/BookRegionSection.tsx
// 예시
---
- 백엔드에 테스트를 위한 더미데이터를 추가했습니다. 잘 작동하는거까지 확인했고, 추후에 글 등록 기능이 구현되면 다시 수정하겠습니다.
---
closed #1 (#닫고싶은 이슈번호)
> Fix/3 메인페이지 백엔드와 API 연결 설정

- backend/bookbook/src/main/java/com/bookbook/BookbookApplication.java
- backend/bookbook/src/main/java/com/bookbook/domain/user/controller/UserController.java
- backend/bookbook/src/main/java/com/bookbook/domain/user/dto/UserLoginRequestDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/user/dto/UserResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/user/entity/User.java
- backend/bookbook/src/main/java/com/bookbook/domain/user/service/UserService.java
- backend/bookbook/src/main/java/com/bookbook/global/security/securityConfig.java
- backend/bookbook/src/main/resources/application-dev.yml
초기 설정 및 개발 환경 구축
보안 및 인증/인가 시스템 강화
개발 및 테스트 편의 기능 추가
---
closed #15 (#닫고싶은 이슈번호)
> [feat] 소셜 로그인 구현 전 기반 작업 (#15)

- backend/bookbook/src/main/java/com/bookbook/domain/home/controller/HomeController.java
- backend/bookbook/src/main/java/com/bookbook/domain/home/dto/HomeResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/home/entity/Book.java
- backend/bookbook/src/main/java/com/bookbook/domain/home/repository/BookRepository.java
- backend/bookbook/src/main/java/com/bookbook/domain/home/service/HomeService.java
- backend/bookbook/src/main/java/com/bookbook/global/config/WebConfig.java
- backend/bookbook/src/main/java/com/bookbook/global/rsdata/RsData.java
- backend/bookbook/src/main/java/com/bookbook/global/security/securityConfig.java
// 예시
-[x] config 쪽에서 bookbook/home 권한이 없어서 못불러오더라고요 그래서 그 부분 추가했습니다.
-[x] 나머지는 실제 사용 방법으로 기능을 바꿨습니다. 즉 home 폴더 하나로 구성하였습니다.
-[x] Webconfig에 GET POST... 등 구현이 없어서 추가하였습니다.,
-[x] RS데이터를 추가해서 성공 응답 생성 메서드, 실패 응답 생성 메서드를 추가했습니다! 나중에 추가하실 분은 추가해도 될거 같아요!
---
- 테스트 더미 삭제, 실제 구현용으로 수정
---
closed #1 (#닫고싶은 이슈번호)
> 더미 파일 쪽이 폴더 생성도 많고 헷갈리게 할거 같아서 제거했습니다.

- frontend/src/app/bookbook/wishlist/page.tsx
찜 목록 페이지에 사이드바가 출력되도록 했습니다.
---
머지 충돌을 해결했습니다.
---
closed #31
> [feat] 찜 목록 페이지에 사이드바 적용

- frontend/src/app/components/UserSidebar.tsx
---
사이드바 스타일을 헤더 및 콘텐츠 영역과 통일감이 있도록 수정했습니다.
---
closed #31
> [style] 전체 레이아웃에 맞춰 UserSidebar 스타일 다듬음

- backend/bookbook/src/main/java/com/bookbook/domain/wishList/controller/WishListController.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/dto/WishListCreateRequestDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/dto/WishListResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/entity/WishList.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/repository/WishListRepository.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/service/WishListService.java
// 예시
---
- 기존에 컴파일 오류를 방지하기 위해 rent 연동 부분들을 주석처리했던 것을 다시 활성화했습니다
---
closed #6
> [feat] WishListService에 Rent 연동 기능 활성화

- backend/bookbook/src/main/java/com/bookbook/domain/user/controller/UserController.java
- backend/bookbook/src/main/java/com/bookbook/domain/user/service/UserService.java
- backend/bookbook/src/main/java/com/bookbook/global/config/AppConfig.java
- backend/bookbook/src/main/java/com/bookbook/global/security/CustomOAuth2UserService.java
- backend/bookbook/src/main/java/com/bookbook/global/security/securityConfig.java
- backend/bookbook/src/main/java/com/bookbook/global/util/NicknameGenerator.java
- backend/bookbook/src/main/resources/application.yml
// 예시
---
---
closed #50  (#닫고싶은 이슈번호)
> [fix] 순환 참조 문제 해결 및 url api/v1 으로 변경

- frontend/src/app/bookbook/ClientLayout.tsx
- frontend/src/app/bookbook/user/signup/page.tsx
- frontend/src/app/components/LoginModal.tsx
- frontend/src/app/components/OAuth/NaverLoginButton.tsx
// 예시
---
---
closed #45  (#닫고싶은 이슈번호)
> [feat] 로그인 모달 수정 및 회원가입 페이지 작성(#45)

- backend/bookbook/src/main/java/com/bookbook/domain/user/controller/UserController.java
- backend/bookbook/src/main/java/com/bookbook/domain/user/dto/UserResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/user/service/UserService.java
- backend/bookbook/src/main/java/com/bookbook/global/security/securityConfig.java
- frontend/next.config.ts
- frontend/src/app/bookbook/user/profile/page.tsx
- frontend/src/app/components/Header.tsx
- frontend/src/app/components/UserSidebar.tsx
// 예시
---
---
closed #85  (#닫고싶은 이슈번호)
> [feat]유저 관련 메서드 백엔드, 프론트 연동 및 자잘한 ui 수정(#85)

- frontend/src/app/bookbook/user/notification/page.tsx
// 예시
---
---
아직 없습니다. 수정 가능성이 있습니다. (#닫고싶은 이슈번호)
> fix/49  NotificationPage 로그인 페이지와 연동

- backend/bookbook/src/main/java/com/bookbook/domain/lendList/controller/LendListController.java
- backend/bookbook/src/main/java/com/bookbook/domain/lendList/service/LendListService.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentList/controller/RentListController.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentList/repository/RentListRepository.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentList/service/RentListService.java
- backend/bookbook/src/main/java/com/bookbook/domain/review/service/ReviewService.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/controller/WishListController.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/service/WishListService.java
// 예시
---
- 머지 충돌을 해결했습니다.
- 메서드들의 목적과 기능에 대한 주석을 추가했습니다.
- 빌려준 사람과 빌려간 사람에 대한 구분이 어려워서 주석을 추가했고, 하는 김에 기타 메서드들에도 간단히 주석을 추가했습니다.
---
#79
> [feat] 머지 충돌 해결 및 코드 목적과 기능에 대한 주석 추가

- backend/bookbook/src/main/java/com/bookbook/domain/lendList/controller/LendListController.java
- backend/bookbook/src/main/java/com/bookbook/domain/lendList/dto/LendListResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/lendList/service/LendListService.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentList/dto/RentListResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentList/service/RentListService.java
- backend/bookbook/src/main/java/com/bookbook/domain/review/controller/ReviewController.java
- backend/bookbook/src/main/java/com/bookbook/domain/review/dto/ReviewResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/review/service/ReviewService.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/dto/WishListResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/service/WishListService.java
---
---
closed #105 (#닫고싶은 이슈번호)
> [feat] 내 도서 하위 페이지들 백엔드 개선

- frontend/src/app/components/BookRegionSection.tsx
> fix: 백엔드 수정으로 인한 프론트 수정

- backend/bookbook/src/main/java/com/bookbook/domain/rent/controller/BookSearchController.java
- backend/bookbook/src/main/java/com/bookbook/domain/rent/controller/ImageUploadController.java
- backend/bookbook/src/main/java/com/bookbook/domain/rent/dto/RentListResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/global/util/ImageManagementController.java
> merge하다가 조금 날아갔더라고요 수정해서 다시 올립니다.

- frontend/src/app/components/Header.tsx
> [fix] 머지 충돌 해결

- backend/bookbook/src/main/java/com/bookbook/domain/rent/controller/RentController.java
- backend/bookbook/src/main/java/com/bookbook/domain/rent/dto/RentAvailableResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/rent/repository/RentRepository.java
- backend/bookbook/src/main/java/com/bookbook/domain/rent/service/RentService.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentBookList/controller/RentBookListController.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentBookList/dto/RentBookListResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentBookList/service/RentBookListService.java
// 예시
-  테스트해보았고, 로그인 로그아웃 상태에서 정상 작동됩니다. 그리고 db도 삭제하고 실행해봐도 아무 이상 없이 잘 작동한거 확인했습니다.
---
(#닫고싶은 이슈번호)
> Feat/117 책 빌리러 가기 백엔드 기능 구현

- frontend/src/app/bookbook/rent/page.tsx
> Feat/116 책 빌리러가기 백엔드와 api 연동

- backend/bookbook/src/main/java/com/bookbook/domain/lendList/controller/LendListController.java
- backend/bookbook/src/main/java/com/bookbook/domain/lendList/repository/LendListRepository.java
- backend/bookbook/src/main/java/com/bookbook/domain/lendList/service/LendListService.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentList/controller/RentListController.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentList/service/RentListService.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/controller/WishListController.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/service/WishListService.java
- frontend/src/app/bookbook/user/lendlist/page.tsx
- frontend/src/app/bookbook/user/rentlist/page.tsx
- frontend/src/app/bookbook/user/wishlist/page.tsx
// 예시
---
- 멘토링에서의 조언대로 검색 필터링을 서버 사이드 방식으로 변경했습니다.
---
closed #139
> [refactor] 서버 사이드 검색 필터링 방식으로 변경

- backend/bookbook/src/main/java/com/bookbook/domain/lendList/controller/LendListController.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentList/controller/RentListController.java
- backend/bookbook/src/main/java/com/bookbook/domain/review/controller/ReviewController.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/controller/WishListController.java
- frontend/src/app/bookbook/user/lendlist/page.tsx
- frontend/src/app/bookbook/user/rentlist/page.tsx
- frontend/src/app/bookbook/user/wishlist/page.tsx
모든 API 응답을 RsData<T> 형식으로 통일했습니다.
---
---
> [refactor] 모든 API 응답을 RsData<T> 형식으로 통일

- backend/bookbook/src/main/java/com/bookbook/domain/report/dto/ReportRequestDto.java
- frontend/next.config.ts
- frontend/src/app/components/ReportModal.tsx
- frontend/src/app/components/UserProfileModal.tsx
---
현재 개발 중이신 게시글 기능과 연동 시 문제가 발생할 것을 생각해서 게시글 연동은 아직 보류중입니다.
대신, 모달 기능이 정상적으로 작동하는지 확인하기 위해 별도로 테스트를 진행했습니다
데이터베이스에 신고 내용이 정상적으로 저장되는 것을 확인했고, 게시글 작성자의 정보(닉네임, 매너점수 등)가 모달에 정확히 표시되는 것을 확인했습니다.
---
closed #151 (#닫고싶은 이슈번호)
> [feat]  신고 모달, 유저 프로필 모달 백엔드 와 연동 (#151)

- backend/bookbook/src/main/java/com/bookbook/domain/wishList/dto/WishListResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/entity/WishList.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/enums/WishListStatus.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/repository/WishListRepository.java
- backend/bookbook/src/main/java/com/bookbook/domain/wishList/service/WishListService.java
// 예시
---
---
closed #161  (#닫고싶은 이슈번호)
> [feat]위시리스트 Soft Delete 기능 구현 및 관련 로직 수정

- frontend/src/app/bookbook/rent/page.tsx
> fix/125-2 책 빌리러 가기 페이지 아래 페이지 이동 수정

- backend/bookbook/src/main/java/com/bookbook/domain/lendList/repository/LendListRepository.java
- backend/bookbook/src/main/java/com/bookbook/domain/lendList/service/LendListService.java
[x] 내가 등록한 도서 삭제 기능에 논리적 삭제(Soft Delete) 적용
---
-  논리적 삭제 게시글을 '내가 등록한  조회 결과에서 제외하도록 쿼리 개선했습니다.
- rentStatus에 'DELETE'가 추가되기 전까진 status를 가져오는 부분을 주석처리했습니다.
---
closed #171  (#닫고싶은 이슈번호)
> [feat]: 내가 등록한 게시글 soft delete 기능 구현

- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/bookbook/layout.tsx
- frontend/src/app/bookbook/rent/[id]/page.tsx
- frontend/src/app/bookbook/user/profile/page.tsx
- frontend/src/app/bookbook/user/signup/page.tsx
- frontend/src/app/components/Header.tsx
- frontend/src/app/components/ReportModal.tsx
- frontend/src/app/components/UserProfileModal.tsx
- frontend/src/app/components/WithdrawalModal.tsx
---
---
closed #170 (#닫고싶은 이슈번호)
> [feat] 유저 프로필 모달 글 상세 페이지에 연결 및 회원탈퇴시 회원탈퇴 여부를 묻는 모달창 추가 (#170)

- backend/bookbook/src/main/java/com/bookbook/domain/user/service/UserService.java
- backend/bookbook/src/main/java/com/bookbook/global/security/securityConfig.java
- frontend/src/app/bookbook/rent/[id]/page.tsx
---
---
closed #182  (#닫고싶은 이슈번호)
> [fix] 글 상세 페이지에서 생기는 fetch 오류 해결(#182)

- backend/bookbook/src/main/java/com/bookbook/domain/report/controller/ReportAdminController.java
- backend/bookbook/src/main/java/com/bookbook/domain/report/dto/response/ReportDetailResponseDto.java
- frontend/src/app/admin/dashboard/_components/mainContent/reportHistoryComponent.tsx
- frontend/src/app/admin/dashboard/_components/report/filter/index.ts
- frontend/src/app/admin/dashboard/_components/report/filter/reportFilterContainer.tsx
- frontend/src/app/admin/dashboard/_components/report/filter/reportStatusFilter.tsx
- frontend/src/app/admin/dashboard/_components/report/manage/reportBasicInfo.tsx
- frontend/src/app/admin/dashboard/_components/report/manage/reportDetailModal.tsx
- frontend/src/app/admin/dashboard/_components/report/manage/reportDetailWithUserModal.tsx
- frontend/src/app/admin/dashboard/_components/report/manage/reportInfo.tsx
- frontend/src/app/admin/dashboard/_components/report/manage/reportStatusInfo.tsx
- frontend/src/app/admin/dashboard/_types/report.ts
관리자 신고 목록/관리 기능을 추가했습니다.
신고한 사람, 신고당한 사람, 신고 처리 여부 등 간단한 정보를 리스트로 보여주고, 버튼을 통해 세부 내용을 확인하실 수 있습니다.
* 클릭 시 상세 내용을 모달로 표기 -> 최초 확인 시 REVIEWED 상태로 변경
* 신고자 정지 or 신고당한 자 정지로 이어지도록
* 조치 후 처리 완료 버튼 클릭 시, PROCESSED로 변경
---
- 정책에 대한 미결정으로 인해 현재는 신고 하나에 대해서만 하나씩 처리할 수 있게 되어 있습니다.
- 추후 수정될 여지는 있습니다.
---
<details>
<summary>기본</summary>
</details>
<details>
<summary>상세 정보</summary>
</details>
<details>
<summary>처리 완료 된 신고 상세 정보</summary>
</details>
closed #166
> Feat/166 신고 목록/관리 기능 추가

- frontend/src/app/bookbook/rent/page.tsx
- frontend/src/app/bookbook/user/notification/page.tsx
- frontend/src/app/components/BookRegionSection.tsx
> fix 이미지 파일 삭제시 무한 GET 요청  방지

- backend/bookbook/src/main/java/com/bookbook/domain/rentList/repository/RentListRepository.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentList/service/RentListService.java
- frontend/src/app/bookbook/user/rentlist/RentListCard.tsx
> fix: 머지 충돌 해결

- frontend/src/app/components/ReviewModal.tsx
> [refactor] ReviewModal 컴포넌트의 이미지 URL 및 UI 개선

- backend/bookbook/src/main/java/com/bookbook/global/security/securityConfig.java
---
---
closed #214  (#닫고싶은 이슈번호)
> [feat] 프론트엔드 배포 도메인 cors 설정 추가(#214)

- backend/bookbook/src/main/java/com/bookbook/domain/rentList/controller/RentListController.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentList/dto/RentListResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentList/entity/RentRequestStatus.java
- backend/bookbook/src/main/java/com/bookbook/domain/rentList/service/RentListService.java
- frontend/src/app/bookbook/user/lendlist/page.tsx
- frontend/src/app/bookbook/user/rentlist/RentListCard.tsx
---
---
closed #197  (#닫고싶은 이슈번호)
> refactor: 대여 목록 및 반납하기 기능 개선

- backend/bookbook/src/main/java/com/bookbook/domain/chat/controller/ChatController.java
- backend/bookbook/src/main/java/com/bookbook/domain/chat/repository/ChatMessageRepository.java
- backend/bookbook/src/main/java/com/bookbook/domain/chat/service/ChatService.java
> fix: 메시지 패널 삭제 버튼 추가 1차본

- backend/bookbook/src/main/java/com/bookbook/domain/user/controller/UserController.java
- backend/bookbook/src/main/java/com/bookbook/domain/user/dto/UserStatusResponseDto.java
- backend/bookbook/src/main/java/com/bookbook/domain/user/service/UserService.java
- frontend/src/app/bookbook/rent/[id]/page.tsx
- frontend/src/app/bookbook/rent/create/page.tsx
// 예시
---
- 계정 정지 시, 글 생성과 글 조회를 불가능 하게 막았습니다.
---
closed #229
> 계정 정지 시, 글 생성 및 글 조회 불가능 하도록 (alert: 정지된 회원입니다.)

- frontend/src/app/bookbook/MessagePopup/MessagePanel.tsx
- frontend/src/app/bookbook/rent/[id]/page.tsx
> 메시지 창 ui 구조 수정

- backend/bookbook/src/main/java/com/bookbook/domain/lendList/service/LendListService.java
---
- 뒤늦게 오류를 발견해서 push했습니다.
---
> fix: 내가 등록한 도서 삭제 시 Soft Delete 기능 활성화
